# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonSendMessage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSendMessage.setGeometry(QtCore.QRect(270, 390, 51, 31))
        self.pushButtonSendMessage.setObjectName("pushButtonSendMessage")
        self.textEditTypeMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditTypeMessage.setGeometry(QtCore.QRect(10, 390, 251, 31))
        self.textEditTypeMessage.setObjectName("textEditTypeMessage")
        self.textBrowserMessages = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserMessages.setGeometry(QtCore.QRect(10, 71, 311, 301))
        self.textBrowserMessages.setObjectName("textBrowserMessages")
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(210, 40, 113, 25))
        self.lineEditName.setObjectName("lineEditName")
        self.labelUsername = QtWidgets.QLabel(self.centralwidget)
        self.labelUsername.setGeometry(QtCore.QRect(133, 40, 75, 20))
        self.labelUsername.setObjectName("labelUsername")
        self.labelMessenger = QtWidgets.QLabel(self.centralwidget)
        self.labelMessenger.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.labelMessenger.setFont(font)
        self.labelMessenger.setObjectName("labelMessenger")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skill Box Messenger"))
        self.pushButtonSendMessage.setText(_translate("MainWindow", ">"))
        self.textEditTypeMessage.setPlaceholderText(_translate("MainWindow", "message"))
        self.labelUsername.setText(_translate("MainWindow", "Username"))
        self.labelMessenger.setText(_translate("MainWindow", "Messenger"))
